# Generated by Django 5.1.1 on 2024-09-17 16:33

import json
import os

from django.db import migrations


def load_counties(apps, schema_editor):
    County = apps.get_model("app", "County")
    SubCounty = apps.get_model("app", "SubCounty")
    Ward = apps.get_model("app", "Ward")

    # Get the current file's directory and find the JSON file in the same directory
    migration_dir = os.path.dirname(__file__)
    json_file_path = os.path.join(migration_dir, "county_data.json")

    # Read the JSON file
    with open(json_file_path, "r") as f:
        counties = json.load(f)

        for county in counties:
            saved_county, _ = County.objects.get_or_create(name=county["name"])
            for sub_county in county["sub_counties"]:
                saved_sub_county, _ = SubCounty.objects.get_or_create(
                    county=saved_county, name=sub_county["name"]
                )

                for index, ward in enumerate(sub_county["wards"]):
                    saved_ward, _ = Ward.objects.get_or_create(
                        sub_county=saved_sub_county, name=sub_county["wards"][index]
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_ward"),
    ]

    operations = [
        migrations.RunPython(load_counties),
    ]
